name: 'MatrixFilter'
description: 'Provides an easier way to filter matrix elements!'
inputs:
  inputFile:
    description: 'The file that contains the JSON configuration of the matrix includes elements. Must come after a Checkout.'
    required: true
    default: 'matrix_includes.json'
  filter: 
    description: 'The JMESPATH JSON query to apply to the input file.'
    required: true
outputs:
  matrixIncludes:
    description: 'The filtered "strategy.matrix" statement created from filtering the "inputFile".'
runs:
  using: 'node12'
  main: 'dist/index.js'