name: 'Conditional Build Matrix'
author: "JoshuaTheMiller"
description: 'Provides an easier way to filter matrix elements!'
inputs:
  inputFile:
    description: 'The file that contains the JSON configuration of the matrix elements. Must come after a Checkout.'
    required: true
    default: '.github/workflows/matrix_includes.json'
  filter: 
    description: 'The JMESPath JSON query to apply to the input file.'
    required: true
  addInclude:
    description: 'Wrap the output from the JSON query in an "{include: ...}" object.'
    required: false
    default: true
outputs:
  matrix:
    description: 'The filtered "strategy.matrix" statement created from filtering the "inputFile".'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'filter'
  color: 'blue'