name: Sample

on:
  workflow_dispatch:

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2      
      - id: set-matrix
        uses: ./ # Uses an action in the root directory        
        with:
          inputFile: '.github/workflows/matrix_includes.json' # Defaults to 'matrix_includes.json'
          filter: '[?runOn==`${{ github.ref }}` || runOn==`always`]'   
  build:
    needs: matrix_prep
    strategy:      
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    name: Build
    runs-on: ${{ matrix.runs_on }}
    steps:
    - name: Echo
      run: echo "${{ matrix.runOn }}"
